# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'ConexNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ConexNews
  pod 'Toast-Swift', '~> 5.0.1'
  
  target 'ConexNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConexNewsUITests' do
    # Pods for testing
  end

end
